name: Go

on:
  push:
    branches: [v5]
    paths:
      - '**'
  pull_request:
    branches: [v5]
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: "stable"

      - name: Download DynamoDB Local
        run: |
          set -e
          make local-dynamodb

      - name: Test
        run: |
          make test

      - name: Linters
        run: |
          make linters
